In [40]:
import pandas as pd
from sklearn.metrics import DistanceMetric

# load data

In [41]:
df = pd.read_csv('/Users/connorhall/datasets/inst414/module 3 assignment/Public.csv', usecols=['SPECIES', 'STATE'])
df = df.dropna()

In [42]:
# remove unknown species
df = df[~df['SPECIES'].str.contains('unknown|perching birds', case=False)]
df

       STATE                SPECIES
8         CA         American robin
11        LA             Blackbirds
13        NY                  Gulls
14        MI          Mourning dove
15        CA       American kestrel
...      ...                    ...
339266    IN          Chimney swift
339267    WA          Cedar waxwing
339268    IL  Yellow-rumped warbler
339269    VA      European starling
339271    NY           Song sparrow

[182633 rows x 2 columns]

# calculate collision counts

In [43]:
collision_count = pd.crosstab(df['SPECIES'], df['STATE']).stack('STATE')
collision_count

SPECIES             STATE
Acadian flycatcher  AB       0
                    AK       0
                    AL       0
                    AR       0
                    AS       0
                            ..
Zenaida dove        VT       0
                    WA       0
                    WI       0
                    WV       0
                    WY       0
Length: 60635, dtype: int64

### separate species and state index

In [44]:
species = collision_count.index.get_level_values('SPECIES').tolist()
states = collision_count.index.get_level_values('STATE').tolist()

collisions_df = pd.DataFrame({'Species': species, 'State': states})
collisions_df['Count'] = collision_count.values
collisions_df

                  Species State  Count
0      Acadian flycatcher    AB      0
1      Acadian flycatcher    AK      0
2      Acadian flycatcher    AL      0
3      Acadian flycatcher    AR      0
4      Acadian flycatcher    AS      0
...                   ...   ...    ...
60630        Zenaida dove    VT      0
60631        Zenaida dove    WA      0
60632        Zenaida dove    WI      0
60633        Zenaida dove    WV      0
60634        Zenaida dove    WY      0

[60635 rows x 3 columns]

### add collision counts to new dataframe format

In [45]:
# create lists of unique species names and state names
unique_sp = sorted(list(set(species)))
unique_st = sorted(list(set(states)))

In [46]:
# create list of collision count lists
counts = []
for sp in unique_sp:
    sp_filter = collisions_df[collisions_df['Species'] == sp]

    counts.append(sp_filter['Count'].tolist())

In [47]:
# create new dataframe format
collisions_df = pd.DataFrame(counts, columns=unique_st, index=unique_sp)
pd.options.display.max_columns = None
collisions_df

,AB,AK,AL,AR,AS,AZ,BC,CA,CO,CT,DC,DE,FL,FN,GA,GU,HI,IA,ID,IL,IN,KS,KY,LA,MA,MB,MD,ME,MH,MI,MN,MO,MP,MS,MT,NC,ND,NE,NH,NJ,NL,NM,NS,NV,NY,OH,OK,ON,OR,PA,PR,QC,RI,SC,SD,SK,TN,TX,UM,UT,VA,VI,VT,WA,WI,WV,WY
Acadian flycatcher,0,0,0,0,0,0,0,2,0,0,0,0,1,0,4,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,3,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
African collared dove,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
African silverbill,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
African yellow bat,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Alder flycatcher,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yellow-throated vireo,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
Yellow-throated warbler,0,0,0,0,0,0,0,1,1,0,0,0,10,0,0,0,0,0,3,5,2,0,0,0,0,0,0,1,0,0,0,3,0,0,1,0,1,0,0,0,0,0,0,0,1,17,0,0,0,2,0,0,0,5,0,0,1,1,0,1,1,0,0,1,0,0,1
Yuma myotis,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
Zebra dove,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,531,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Zenaida dove,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,0,0,0,0,0,0,0,0,0,0,16,0,0,0,0,0

# analysis

### L1 normalization

In [48]:
df_norm = collisions_df.divide(collisions_df.sum(axis=1), axis=0)
df_norm.head(10)

,AB,AK,AL,AR,AS,AZ,BC,CA,CO,CT,DC,DE,FL,FN,GA,GU,HI,IA,ID,IL,IN,KS,KY,LA,MA,MB,MD,ME,MH,MI,MN,MO,MP,MS,MT,NC,ND,NE,NH,NJ,NL,NM,NS,NV,NY,OH,OK,ON,OR,PA,PR,QC,RI,SC,SD,SK,TN,TX,UM,UT,VA,VI,VT,WA,WI,WV,WY
Acadian flycatcher,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.117647,0.000000,0.0,0.000000,0.0,0.058824,0.00,0.235294,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.058824,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.058824,0.0,0.0,0.00,0.176471,0.00,0.00,0.0,0.058824,0.0,0.0,0.0,0.00,0.000000,0.058824,0.000000,0.0,0.0,0.058824,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.117647,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
African collared dove,0.0,0.000000,0.000000,0.0,0.0,0.250000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.25,0.000000,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.00,0.00,0.0,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.5,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
African silverbill,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.00,0.000000,0.0,1.0,0.0,0.0,0.00,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.00,0.00,0.0,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
African yellow bat,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,1.00,0.000000,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.00,0.00,0.0,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
Alder flycatcher,0.0,0.181818,0.090909,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.00,0.090909,0.0,0.000000,0.0,0.090909,0.0,0.0,0.000000,0.0,0.090909,0.000000,0.181818,0.0,0.0,0.00,0.000000,0.00,0.00,0.0,0.000000,0.0,0.0,0.0,0.00,0.181818,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.090909,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
Alder/willow flycatcher complex,0.0,0.000000,0.000000,0.0,0.0,0.041667,0.0,0.000000,0.041667,0.0,0.041667,0.0,0.083333,0.00,0.041667,0.0,0.0,0.0,0.0,0.00,0.041667,0.0,0.000000,0.0,0.000000,0.0,0.0,0.083333,0.0,0.000000,0.041667,0.000000,0.0,0.0,0.00,0.125000,0.00,0.00,0.0,0.000000,0.0,0.0,0.0,0.00,0.208333,0.000000,0.041667,0.0,0.0,0.041667,0.0,0.0,0.000000,0.000000,0.0,0.0,0.041667,0.083333,0.0,0.0,0.041667,0.0,0.0,0.0,0.0,0.0,0.0
Allen's hummingbird,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,1.000000,0.000000,0.0,0.000000,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.00,0.00,0.0,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
Alligator snapping turtle,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.250000,0.00,0.000000,0.0,0.0,0.0,0.0,0.25,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.00,0.00,0.0,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.250000,0.0,0.0,0.250000,0.0,0.0,0.0,0.0,0.0,0.0
American alligator,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.971429,0.00,0.000000,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.00,0.00,0.0,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.028571,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
American avocet,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.200000,0.100000,0.0,0.000000,0.0,0.050000,0.00,0.000000,0.0,0.0,0.0,0.0,0.05,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.05,0.000000,0.05,0.05,0.0,0.000000,0.0,0.0,0.0,0.05,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.4,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

### find species of interest- high collision counts

In [49]:
df['SPECIES'].value_counts().head(20)

SPECIES
Mourning dove         16854
Killdeer              10963
Barn swallow          10946
American kestrel      10132
Horned lark            8969
Gulls                  7391
European starling      6809
Eastern meadowlark     5027
Rock pigeon            4594
Red-tailed hawk        4366
Sparrows               4314
Cliff swallow          3357
Western meadowlark     2816
Ring-billed gull       2419
American barn owl      2288
Canada goose           2192
Herring gull           2189
American robin         1906
Microbats              1709
Hawks                  1656
Name: count, dtype: int64

In [50]:
target_species = ['American kestrel', 'Horned lark', 'Eastern meadowlark']

### top 10 similar species by euclidean distance

In [51]:
dist = DistanceMetric.get_metric("euclidean")

for species in target_species:

    # get collision counts for target species
    target_species_collisions = df_norm.loc[species]

    #Generating distances from that species to all the others
    distances = dist.pairwise(df_norm, [target_species_collisions])[:,0]

    query_distances = list(zip(df_norm.index, distances))

    # top 10 most similar species
    print(f'{species}:\n')
    for similar_species, similar_state_score in sorted(query_distances, key=lambda x: x[1], reverse=False)[:10]:
        print(similar_species, similar_state_score)
        
    print('\n')

American kestrel:

American kestrel 0.0
Barn swallow 0.11329335771966093
Mallard 0.11670247886973122
Gulls 0.12276302762415234
Hawks 0.12336550987430592
Cooper's hawk 0.12439625484079551
Raccoon 0.1246040114218174
Sparrows 0.12575085047984874
Canada goose 0.13120805076769082
Song sparrow 0.14051700263843536


Horned lark:

Horned lark 0.0
Prairie falcon 0.16936193580624756
Vesper sparrow 0.17624404469850732
Rock wren 0.204955320664166
Western meadowlark 0.23127539482487675
Say's phoebe 0.24480382853163818
Great horned owl 0.24845207672958394
Bullock's oriole 0.24924407895643952
American badger 0.2496670642992617
Pronghorn 0.26314699750024173


Eastern meadowlark:

Eastern meadowlark 0.0
Killdeer 0.12950407671947292
Blackbirds 0.1417391948861779
Raccoon 0.15466922575921563
Purple martin 0.15473842805681554
Barn swallow 0.15528204312524982
European starling 0.16933143899605546
Barred owl 0.17230086347062518
Wrens 0.18037777659686663
Sparrows 0.18242231601546519